FROM node:20-alpine

WORKDIR /app

COPY . .

CMD node hello-world.js

# docker run -it --entrypoint sh hello-world
# docker build -t hello-world .
# docker run hello-world

# docker images
# docker ps
# docker stop <first three letters of id>
# docker rm <first three letters of id> - add --force if necessary
# docker container prune - stops all running container